### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by rmrhz** [ReflectionBrowser/ReflectionBrowser#1]
I would like to contribute to this project and would also like to have some neat features that can make debugging a breeze.

_Feature Requests_
- Composer ready
- Agnostic integration to testing frameworks such as PHPUnit, Codeception, Humbug, etc.
- Documentation(?)

That's all I can think of for now, but will eventually add something along the way.

**Comment by dwlnetnl** [comment]
First, thank you for considering to contribute!

I have spent some time to get nice debuggable error messages. So when there is an error like an undefined variable, you get a nice error page with detailed information about the error, a stack trace and a dump of the variables in scope.

The app was not conceived to use as a debugging solution and inspect the type system and runtime at some breakpoint in a debugger. It is meant to be a browser to get insight in the runtime and it defined functions, classes, methods, constants, etc. So there isn't state, there are no session variables which hold some kind of data between requests.

It's really ment as a drop it in a directory on some server and start exploring the runtime In nice way in stead of programmatically exploring the runtime.

I can help you out on something like IRC about anything you want to know of the implementation and get you started, but I don't have time to keep it around as an active project, sorry. That's one of the reasons I've open sourced it.

**Comment by rmrhz** [comment]
Not a problem, I'll figure a way somehow. This really took my interest quite a lot.

No need for a state, since I just need to trace the stack in an architectural kind of perspective. And I'll be doing most of the debugging behind a CLI
