### ISSUE TITLE
Remove critical dependency on Apache mod_include

### ISSUE THREAD

**Issue by hopeseekr** [ReflectionBrowser/ReflectionBrowser#2]
This project has a hard dependency on the Apache module `mod_include`, which provides `$_SERVER['DOCUMENT_URI']` which is needed on line 112 of RBApplication.php.

Please either remove it (preferred, particularly on WAMP stacks where it is not default) or include it as a hard requirement in the README.

**Comment by dwlnetnl** [comment]
Thanks for reporting!

I didn't realize that it is a hard dependency because in my development environment I don't use Apache/mod_include! But I wil change the line.

**Comment by hopeseekr** [comment]
Holy crap! WAMP users around the world rejoice! The ones enlightened enough to use your project, anyway ::wink::!

**Comment by hopeseekr** [comment]
You need a reward for Most Responsive Githubber of 10 April 2015!

**Comment by dwlnetnl** [comment]
Well, the zero dependency thing (uhm, well..., PHP is **the** dependency) is a big deal for the success of this application!
